### ISSUE TITLE
TypeError on plugin load

### ISSUE THREAD

**Issue by roversch** [ros-visualization/rqt_dep#14]
If I run `rqt_dep`, I directly get a crash, with following output:

```
PluginManager._load_plugin() could not load plugin "rqt_dep/RosPackGraph":
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 106, in load
    return class_ref(plugin_context)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_dep/ros_pack_graph.py", line 152, in __init__
    completionmodel = StackageCompletionModel(self._widget.filter_line_edit, rospack, rosstack)
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_dep/ros_pack_graph.py", line 82, in __init__
    self.allnames = sorted(list(set(rospack.list() + rosstack.list())))
TypeError: unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'
```

with

- `rospkg` version `1.2.9`
- `rqt_dep` version `0.4.10`

**Comment by roversch** [comment]
Accidentally submitted twice -> deleting
