### ISSUE TITLE
Crash in rqt_dep

### ISSUE THREAD

**Issue by felixdivo** [ros-visualization/rqt_dep#3]
I ran the program from the console; and it crashed, after I randomly selected a few checkboxes without having anything inside the package name field. This is the error message:

```
felix@Felix-Laptop:~$ rqt_dep
RosPackageGraphDotcodeGenerator.add_package_descendants_recursively(catkin_pip), parent: pyros_utils: ResourceNotFound: catkin_pip
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/felix/sailing/bord-pc/src
ROS path [2]=/opt/ros/kinetic/share
RosPackageGraphDotcodeGenerator.add_package_descendants_recursively(catkin_pip), parent: pyros_utils: ResourceNotFound: catkin_pip
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/felix/sailing/bord-pc/src
ROS path [2]=/opt/ros/kinetic/share
RosPackageGraphDotcodeGenerator.add_package_descendants_recursively(catkin_pip), parent: pyros_utils: ResourceNotFound: catkin_pip
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/felix/sailing/bord-pc/src
ROS path [2]=/opt/ros/kinetic/share
RosPackageGraphDotcodeGenerator.add_package_descendants_recursively(catkin_pip), parent: pyros_utils: ResourceNotFound: catkin_pip
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/felix/sailing/bord-pc/src
ROS path [2]=/opt/ros/kinetic/share
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_dep/ros_pack_graph.py", line 276, in _update_thread_run
    self._update_graph(self._generate_dotcode())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_dep/ros_pack_graph.py", line 311, in _generate_dotcode
    hide_dry=self._options['package_types'] == 2)                                                                                                                                            
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_dep/dotcode_pack.py", line 150, in generate_dotcode                                                                                 
    self.add_package_descendants_recursively(name)                                                                                                                                           
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_dep/dotcode_pack.py", line 408, in add_package_descendants_recursively                                                              
    parent=package_name)                                                                                                                                                                     
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_dep/dotcode_pack.py", line 390, in add_package_descendants_recursively                                                              
    rosdeps = self.rospack.get_rosdeps(package_name, implicit=implicit)                                                                                                                      
  File "/home/felix/.local/lib/python2.7/site-packages/rospkg/rospack.py", line 347, in get_rosdeps                                                                                          
    m = self.get_manifest(package)                                                                                                                                                           
  File "/home/felix/.local/lib/python2.7/site-packages/rospkg/rospack.py", line 167, in get_manifest                                                                                         
    return self._load_manifest(name)                                                                                                                                                         
  File "/home/felix/.local/lib/python2.7/site-packages/rospkg/rospack.py", line 211, in _load_manifest                                                                                       
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)                                                                             
  File "/home/felix/.local/lib/python2.7/site-packages/rospkg/rospack.py", line 203, in get_path                                                                                             
    raise ResourceNotFound(name, ros_paths=self._ros_paths)                                                                                                                                  
rospkg.common.ResourceNotFound: catkin_pip                                                                                                                                                   
ROS path [0]=/opt/ros/kinetic/share/ros                                                                                                                                                      
ROS path [1]=/home/felix/sailing/bord-pc/src                                                                                                                                                 
ROS path [2]=/opt/ros/kinetic/share                                                                                                                                                          
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by dirk-thomas** [comment]
While #4 addresses the symptom (the UI crashing) it doesn't fix the general problem of the rospack state getting changed while it is being used in a separate thread.

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as May 31st 2025, so I'm closing this.

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
